#!/usr/bin/env python3
"""Generate docs/API.md from the live route table.

Hand-written API prose drifts: the README had 40 routes implemented and 3
undocumented. This reads `api.ROUTES` and the handler docstrings, so the
reference cannot describe endpoints that do not exist, or miss ones that do.

    python3 tools/gen_api_docs.py           # write docs/API.md
    python3 tools/gen_api_docs.py --check   # fail if out of date (for CI)
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tam import api  # noqa: E402
from tam.errors import (AuthError, ConflictError, NotFoundError,  # noqa: E402
                        TransitionError, ValidationError)

# Matched against the READABLE path, in order; first match wins.
SECTIONS = [
    ("Health", r"^/health$"),
    ("Projects", r"^/api/projects"),
    ("Issues", r"^/api/issues(/\{key\})?$"),
    ("Issue detail", r"^/api/issues/\{key\}/(transition|comments|history|links)$"),
    ("Metrics, targets, params", r"(metrics|targets|params|heartbeat)"),
    ("Watches and scanning", r"(watches|scan|providers)"),
    ("Digest and review", r"digest"),
    ("Other", r".*"),
]


def readable(pattern):
    """Turn a route regex back into something a human can read."""
    p = pattern.lstrip("^").rstrip("$")
    p = re.sub(r"\(\?P<key>[^)]*\)", "{key}", p)
    p = re.sub(r"\(\?P<pkey>[^)]*\)", "{project}", p)
    p = re.sub(r"\(\?P<date>[^)]*\)", "{date}", p)
    p = re.sub(r"\(\?P<wid>[^)]*\)", "{watch_id}", p)
    return p.replace("\\d+", "").replace("\\", "")


def describe(fn):
    doc = (fn.__doc__ or "").strip().splitlines()
    return doc[0].strip() if doc else ""


def build():
    rows = []
    for method, pattern, fn, auth in api.ROUTES:
        rows.append((readable(pattern), method, auth, describe(fn), fn.__name__))

    # Assign each route to the first section that matches, in declared order.
    buckets = {title: [] for title, _ in SECTIONS}
    for row in rows:
        for title, rx in SECTIONS:
            if re.search(rx, row[0]):
                buckets[title].append(row)
                break

    out = []
    out.append("# TAM HTTP API\n")
    out.append("*Generated by `tools/gen_api_docs.py` — do not edit by hand.*\n")
    out.append(f"{len(rows)} endpoints. Base URL is `http://<db_host>:8787`; on this "
               "cluster that is the host named in `db_host` in `data/config.json`.\n")

    out.append("## Authentication\n")
    out.append("All routes except `/health` require a bearer token:\n")
    out.append("```sh\ncurl -H \"Authorization: Bearer $(cat data/api_token)\" \\\n"
               "     'http://127.0.0.1:8787/api/issues?overdue=1'\n```\n")
    out.append("The token is generated at `tam init` with mode 600. There is one "
               "shared token: it carries no per-caller identity and cannot be "
               "revoked individually.\n")

    out.append("## Response envelope\n")
    out.append("```json\n"
               '{"ok": true,  "data": {...}, "meta": {"count": 3}}\n'
               '{"ok": false, "error": {"code": "not_found", "message": "..."}}\n'
               "```\n")

    out.append("## Error codes\n")
    out.append("| code | HTTP | meaning |\n|---|---|---|")
    for cls in (ValidationError, AuthError, NotFoundError, ConflictError,
                TransitionError):
        out.append(f"| `{cls.code}` | {cls.http_status} | "
                   f"{cls.__doc__ or cls.__name__} |")
    out.append("")

    for title, _ in SECTIONS:
        matched = buckets[title]
        if not matched:
            continue
        out.append(f"## {title}\n")
        out.append("| method | path | auth | description |\n|---|---|---|---|")
        for path, method, auth, desc, _ in sorted(matched, key=lambda r: (r[0], r[1])):
            out.append(f"| `{method}` | `{path}` | {'yes' if auth else 'no'} | {desc} |")
        out.append("")

    out.append("## Filters\n")
    out.append("`GET /api/issues` accepts the same filter names as the CLI flags. "
               "Multi-valued filters take a comma-separated list or repeated "
               "parameters.\n")
    from tam.core.query import (BOOL_FIELDS, DATE_FIELDS, INT_FIELDS,
                                MULTI_FIELDS, STR_FIELDS)
    for name, group in (("multi-valued", MULTI_FIELDS), ("text", STR_FIELDS),
                        ("dates", DATE_FIELDS), ("booleans", BOOL_FIELDS),
                        ("integers", INT_FIELDS)):
        out.append(f"- **{name}**: " + ", ".join(f"`{f}`" for f in group))
    out.append("\nUnknown filter names are rejected with `400 validation`.\n")

    out.append("## Notes\n")
    out.append("- Status changes go through `POST /api/issues/{key}/transition`, "
               "never `PATCH`. The workflow matrix and its guards are enforced "
               "server-side and cannot be bypassed by any client.\n")
    out.append("- Write endpoints accept an `actor` field; it is recorded in the "
               "audit log. Give each agent its own actor name.\n")
    out.append("- `GET /api/events?since=<iso>` is a change feed built on the audit "
               "log — cheaper for an agent to poll than re-reading the board.\n")
    out.append("- There is no optimistic concurrency: simultaneous writes to one "
               "issue are serialised, but the later one wins silently. Agents are "
               "expected to work on disjoint issues.\n")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if docs/API.md is out of date")
    args = ap.parse_args()

    target = ROOT / "docs" / "API.md"
    content = build()
    if args.check:
        current = target.read_text() if target.exists() else ""
        if current != content:
            print("docs/API.md is out of date; run tools/gen_api_docs.py")
            sys.exit(1)
        print("docs/API.md is current")
    else:
        target.parent.mkdir(exist_ok=True)
        target.write_text(content)
        print(f"wrote {target} ({len(api.ROUTES)} endpoints)")
